

CREATE TABLE UTILISATEUR (
    numUTILISATEUR INTEGER NOT NULL AUTO_INCREMENT,
    nom VARCHAR(50) NOT NULL ,
    prenom VARCHAR(50) NOT NULL ,
    age INTEGER NOT NULL ,
    adresse VARCHAR(50) NOT NULL ,
    login VARCHAR(50) NOT NULL ,
    motDePasse VARCHAR(50) NOT NULL ,
    numClub INTEGER NOT NULL ,
    PRIMARY KEY (numUTILISATEUR),
    FOREIGN KEY (numClub) REFERENCES DIRIGE (numClub)
);

CREATE TABLE PRESIDENT (
    numPresident INTEGER NOT NULL ,
    prime VARCHAR(50) NOT NULL ,
    PRIMARY KEY (numPresident),
    FOREIGN KEY (numPresident) REFERENCES UTILISATEUR(numUTILISATEUR)
);

CREATE TABLE EVALUATEUR (
    numEvaluateur INTEGER NOT NULL ,
    specialite VARCHAR(50) NOT NULL ,
    PRIMARY KEY (numEvaluateur),
    FOREIGN KEY (numEvaluateur) REFERENCES UTILISATEUR(numUTILISATEUR)
);

